@poorManReddit_HostAddress = http://localhost:5070

POST {{poorManReddit_HostAddress}}/addTopic/
Accept: application/json
Body: {"id":7,"topic_id":1728947842828,"title":"a new topic","content":"hooray","rating":0}